### ISSUE TITLE
Clicking on link to same-page anchor does not jump to anchor id

### ISSUE THREAD

**Issue by jimbo1qaz** [rNeomy/reader-view#52]
Procedure:

- Install https://addons.mozilla.org/en-US/firefox/addon/readability-based-reader-view/ on Firefox.
- Visit http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2271.html
- Enable reader view
- Click the link: [ISO 14882 (1998)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2271.html#cpp_standard) which jumps to an anchor id on the page.

Result:

- I get 2 copies of the reader view left-side-bar, and the page jumps to the very top, instead of #cpp_standard.

If I middle-click the anchor, I instead get http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2271.html in a new tab (not in reader view, and links to the top of the page rather than the anchor id).

**Comment by rNeomy** [comment]
Thanks for the report. Should be fixed by the next release.

**Comment by nyanpasu64** [comment]
Still happens on Reader View 0.3.9 (Mar 29, 2020) on Firefox 77.0.1.
